### ISSUE TITLE
Question: How to edit configurator

### ISSUE THREAD

**Issue by MatthewJohn** [inbucket/inbucket.org#6]
The code for this in `configurator` dir appears to be minified... is the raw source available to edit to add new configuration options?

**Comment by jhillyerd** [comment]
Yes, it's part of this repo: https://github.com/inbucket/inbucket.org/tree/master/vue-configurator (vue is the JS framework it uses)

It looks like the Vue outputDir is already points to the root /configurator link, so I believe a npm run build will update that.

While you are in there, could you also run an `npm audit fix` + build, and send that as a separate PR? Cheers.

**Comment by MatthewJohn** [comment]
Sure thing :) Thank you
